<?php

/** @return array<int, list<array{key: string, label: string, multiple: bool}>> */
$one = fn (string $key, string $label, bool $multiple) => ['key' => $key, 'label' => $label, 'multiple' => $multiple];

return [
    1 => [
        $one('L1_business_vision', 'Business Vision', false),
        $one('L1_business_goals', 'Business Goals', true),
        $one('L1_business_objectives', 'Business Objectives', true),
        $one('L1_kpis', 'KPIs / Success Metrics', true),
        $one('L1_business_constraints', 'Business Constraints', true),
        $one('L1_priorities_tradeoffs', 'Priorities / Trade-offs', true),
        $one('L1_success_criteria', 'Success Criteria (Definition of Success)', false),
        $one('L1_decision_rules', 'Decision Rules', true),
    ],
    2 => [
        $one('L2_brd', 'BRD', false),
        $one('L2_business_rules', 'Business rules', true),
        $one('L2_stakeholders', 'Stakeholders', true),
        $one('L2_business_requirements_formal', 'Business Requirements (формализованные)', true),
        $one('L2_stakeholder_requirements', 'Stakeholder Requirements', true),
        $one('L2_constraints', 'Constraints (регуляторка, сроки, бюджет)', true),
        $one('L2_scope', 'Scope (включая in / out)', false),
        $one('L2_assumptions', 'Assumptions', true),
        $one('L2_dependencies', 'Dependencies', true),
    ],
    3 => [
        $one('L3_bpmn', 'BPMN (AS-IS / TO-BE)', true),
        $one('L3_business_use_cases', 'Business Use Cases', true),
        $one('L3_value_streams', 'Value Streams', true),
        $one('L3_process_maps', 'Process Maps', true),
        $one('L3_error_flows', 'Error Flows', true),
        $one('L3_alternative_flows', 'Alternative Flows', true),
        $one('L3_system_boundaries', 'System Boundaries', false),
        $one('L3_external_internal', 'External vs Internal interactions', true),
    ],
    4 => [
        $one('L4_epics', 'Epics', true),
        $one('L4_user_stories', 'User Stories / Features', true),
        $one('L4_acceptance_criteria', 'Acceptance Criteria', true),
        $one('L4_definition_of_done', 'Definition of Done', true),
        $one('L4_backlog', 'Backlog (prioritized)', true),
        $one('L4_traceability', 'Traceability (связь с L2 / L3)', true),
        $one('L4_dependencies', 'Dependencies (между задачами)', true),
    ],
    5 => [
        $one('L5_system_use_cases', 'System Use Cases', true),
        $one('L5_actors', 'Actors', true),
        $one('L5_external_systems', 'External Systems', true),
        $one('L5_system_boundary', 'System boundary', false),
        $one('L5_c4_context', 'C4 Level 1 — System Context Diagram', true),
        $one('L5_system_use_case_diagrams', 'System Use Case Diagrams', true),
        $one('L5_api_interactions', 'API interactions (high-level)', true),
        $one('L5_events', 'Events (publish/subscribe)', true),
        $one('L5_data_flows', 'Data flows (input/output)', true),
        $one('L5_integration_points', 'Integration points', true),
        $one('L5_interaction_patterns', 'Interaction patterns (sync / async)', true),
    ],
    6 => [
        $one('L6_sequence_diagrams', 'Sequence Diagrams', true),
        $one('L6_activity_diagrams', 'Activity Diagrams', true),
        $one('L6_state_machine', 'State Machine Diagrams', true),
        $one('L6_communication_diagrams', 'Communication Diagrams', true),
        $one('L6_error_flows', 'Error flows', true),
        $one('L6_retry_timeout', 'Retry / timeout logic', true),
        $one('L6_async_flows', 'Async flows', true),
    ],
    7 => [
        $one('L7_domain_models', 'Domain Models', false),
        $one('L7_high_level_class', 'High-level Class Diagrams', true),
        $one('L7_er_diagrams', 'ER Diagrams (логическая модель)', true),
        $one('L7_detailed_class', 'Detailed Class Diagrams', true),
        $one('L7_entity_lifecycle', 'Entity Lifecycle', true),
        $one('L7_package_diagrams', 'Package Diagrams', true),
        $one('L7_object_diagrams', 'Object Diagrams', true),
    ],
    8 => [
        $one('L8_c4_container', 'C4 Level 2 — Container Diagram', true),
        $one('L8_c4_component', 'C4 Level 3 — Component Diagram', true),
        $one('L8_uml_component', 'UML Component Diagrams', true),
        $one('L8_integration_diagrams', 'Integration Diagrams', true),
        $one('L8_data_flow_diagrams', 'Data Flow Diagrams', true),
        $one('L8_adr', 'Architecture Decision Records (ADR)', true),
        $one('L8_interaction_patterns', 'Interaction patterns (sync / async)', true),
        $one('L8_data_ownership', 'Data ownership map', false),
    ],
    9 => [
        $one('L9_deployment_diagrams', 'Deployment Diagrams (UML)', true),
        $one('L9_infrastructure_diagrams', 'Infrastructure Diagrams (Cloud / On-prem)', true),
        $one('L9_cloud_architecture', 'Cloud Architecture', false),
        $one('L9_kubernetes', 'Kubernetes / Containers', false),
        $one('L9_network_topology', 'Network topology', false),
        $one('L9_load_balancers', 'Load balancers', true),
        $one('L9_api_gateways', 'API gateways', true),
        $one('L9_monitoring_logging', 'Monitoring & Logging architecture', false),
        $one('L9_cicd', 'CI/CD pipelines', true),
        $one('L9_environment_setup', 'Environment setup (dev / test / prod)', false),
    ],
    10 => [
        $one('L10_openapi', 'API: OpenAPI / REST', true),
        $one('L10_graphql', 'API: GraphQL', true),
        $one('L10_soap', 'API: SOAP (WSDL)', true),
        $one('L10_event_schemas', 'Event schemas', true),
        $one('L10_async_contracts', 'Async contracts', true),
        $one('L10_db_schema', 'DB schema (physical model)', false),
        $one('L10_migration_scripts', 'Migration scripts', true),
        $one('L10_dto_contracts', 'DTO / Data contracts', true),
        $one('L10_validation_rules', 'Validation rules', true),
        $one('L10_error_models', 'Error models (ошибки API)', true),
        $one('L10_versioning', 'Versioning strategy', false),
    ],
];
