<?php

/**
 * Превью не-изображений: иконки vscode-icons (MIT), CDN jsDelivr — см. AttachmentFileIcon::VSCODE_ICONS_TAG.
 * Сначала подстроки имени файла (регистронезависимо), затем расширение.
 *
 * @return array{patterns: list<array{contains: string, icon: string, label: string}>, extensions: array<string, array{icon: string, label: string}>}
 */
return [
    'patterns' => [
        ['contains' => 'postman', 'icon' => 'postman', 'label' => 'Postman'],
        ['contains' => 'soapui', 'icon' => 'xml', 'label' => 'SoapUI'],
        ['contains' => 'insomnia', 'icon' => 'insomnia', 'label' => 'Insomnia'],
        ['contains' => 'swagger', 'icon' => 'swagger', 'label' => 'Swagger'],
        ['contains' => 'openapi', 'icon' => 'swagger', 'label' => 'OpenAPI'],
        ['contains' => 'asyncapi', 'icon' => 'swagger', 'label' => 'AsyncAPI'],
        ['contains' => 'graphql', 'icon' => 'graphql', 'label' => 'GraphQL'],
        ['contains' => 'camunda', 'icon' => 'xml', 'label' => 'Camunda'],
        ['contains' => 'kubernetes', 'icon' => 'helm', 'label' => 'Kubernetes'],
        ['contains' => 'docker', 'icon' => 'docker', 'label' => 'Docker'],
        ['contains' => 'jenkins', 'icon' => 'jenkins', 'label' => 'Jenkins'],
        ['contains' => 'gitlab', 'icon' => 'gitlab', 'label' => 'GitLab'],
        ['contains' => 'github', 'icon' => 'github', 'label' => 'GitHub'],
        ['contains' => 'terraform', 'icon' => 'terraform', 'label' => 'Terraform'],
        ['contains' => 'ansible', 'icon' => 'ansible', 'label' => 'Ansible'],
        ['contains' => 'prometheus', 'icon' => 'prometheus', 'label' => 'Prometheus'],
        ['contains' => 'grafana', 'icon' => 'grafana', 'label' => 'Grafana'],
        ['contains' => 'nginx', 'icon' => 'nginx', 'label' => 'Nginx'],
        ['contains' => 'kafka', 'icon' => 'apachekafka', 'label' => 'Kafka'],
        ['contains' => 'elastic', 'icon' => 'elastic', 'label' => 'Elastic'],
        ['contains' => 'mongodb', 'icon' => 'mongo', 'label' => 'MongoDB'],
        ['contains' => 'postgresql', 'icon' => 'pgsql', 'label' => 'PostgreSQL'],
        ['contains' => 'mysql', 'icon' => 'mysql', 'label' => 'MySQL'],
        ['contains' => 'redis', 'icon' => 'sql', 'label' => 'Redis'],
        ['contains' => 'package.json', 'icon' => 'npm', 'label' => 'npm / Node'],
        ['contains' => 'pom.xml', 'icon' => 'maven', 'label' => 'Maven'],
        ['contains' => 'build.gradle', 'icon' => 'gradle', 'label' => 'Gradle'],
    ],

    'extensions' => [
        'bpmn' => ['icon' => 'xml', 'label' => 'BPMN'],
        'cmmn' => ['icon' => 'xml', 'label' => 'CMMN'],
        'dmn' => ['icon' => 'xml', 'label' => 'DMN'],
        'drawio' => ['icon' => 'drawio', 'label' => 'draw.io / diagrams.net'],
        'dio' => ['icon' => 'drawio', 'label' => 'draw.io / diagrams.net'],
        'uml' => ['icon' => 'mermaid', 'label' => 'UML / диаграмма'],
        'puml' => ['icon' => 'mermaid', 'label' => 'PlantUML'],
        'plantuml' => ['icon' => 'mermaid', 'label' => 'PlantUML'],
        'xmi' => ['icon' => 'eclipse', 'label' => 'XMI / модель'],
        'mdj' => ['icon' => 'json', 'label' => 'StarUML (.mdj)'],
        'pdf' => ['icon' => 'pdf', 'label' => 'PDF'],
        'doc' => ['icon' => 'word', 'label' => 'Word'],
        'docx' => ['icon' => 'word', 'label' => 'Word'],
        'xls' => ['icon' => 'excel', 'label' => 'Excel'],
        'xlsx' => ['icon' => 'excel', 'label' => 'Excel'],
        'ppt' => ['icon' => 'powerpoint', 'label' => 'PowerPoint'],
        'pptx' => ['icon' => 'powerpoint', 'label' => 'PowerPoint'],
        'md' => ['icon' => 'markdown', 'label' => 'Markdown'],
        'markdown' => ['icon' => 'markdown', 'label' => 'Markdown'],
        'zip' => ['icon' => 'zip', 'label' => 'Архив'],
        '7z' => ['icon' => 'zip', 'label' => 'Архив'],
        'rar' => ['icon' => 'zip', 'label' => 'Архив'],
        'gz' => ['icon' => 'gnu', 'label' => 'Архив'],
        'tar' => ['icon' => 'gnu', 'label' => 'Архив'],
        'sql' => ['icon' => 'sql', 'label' => 'SQL'],
        'wsdl' => ['icon' => 'xml', 'label' => 'WSDL / XML'],
        'yaml' => ['icon' => 'yaml', 'label' => 'YAML'],
        'yml' => ['icon' => 'yaml', 'label' => 'YAML'],
        'xml' => ['icon' => 'xml', 'label' => 'XML'],
        'json' => ['icon' => 'json', 'label' => 'JSON'],
        'proto' => ['icon' => 'protobuf', 'label' => '.proto / Protobuf'],
        'avro' => ['icon' => 'avro', 'label' => 'Apache Avro'],
        'toml' => ['icon' => 'toml', 'label' => 'TOML'],
    ],
];
